// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVLdCtIgA0wIRRl4KychNstQGcqWkouCc',
    appId: '1:297437106545:web:4a41c088c033f96737e6d0',
    messagingSenderId: '297437106545',
    projectId: 'gre-quizmaster',
    authDomain: 'gre-quizmaster.firebaseapp.com',
    storageBucket: 'gre-quizmaster.firebasestorage.app',
    measurementId: 'G-VEZ5GES4LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0pexj1gH7H2nQD7ZnFRY6gpEqGMuEN8',
    appId: '1:297437106545:android:43b791672963d7f637e6d0',
    messagingSenderId: '297437106545',
    projectId: 'gre-quizmaster',
    storageBucket: 'gre-quizmaster.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-y2WftMdCHThYAO-iFGmbv1z4206Qk4',
    appId: '1:297437106545:ios:74f5ec1de0515c5937e6d0',
    messagingSenderId: '297437106545',
    projectId: 'gre-quizmaster',
    storageBucket: 'gre-quizmaster.firebasestorage.app',
    iosBundleId: 'com.quizmaster.greVocabQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-y2WftMdCHThYAO-iFGmbv1z4206Qk4',
    appId: '1:297437106545:ios:74f5ec1de0515c5937e6d0',
    messagingSenderId: '297437106545',
    projectId: 'gre-quizmaster',
    storageBucket: 'gre-quizmaster.firebasestorage.app',
    iosBundleId: 'com.quizmaster.greVocabQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVLdCtIgA0wIRRl4KychNstQGcqWkouCc',
    appId: '1:297437106545:web:6106d516bac8880737e6d0',
    messagingSenderId: '297437106545',
    projectId: 'gre-quizmaster',
    authDomain: 'gre-quizmaster.firebaseapp.com',
    storageBucket: 'gre-quizmaster.firebasestorage.app',
    measurementId: 'G-PSMG7LKDHB',
  );
}
